# Generated by Django 5.1.1 on 2024-09-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRestfull', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libros_escritos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'autoria',
                'managed': False,
            },
        ),
    ]
